### ISSUE TITLE
Xcode 10 and Swift 4.2 

### ISSUE THREAD

**Issue by CavalcanteLeo** [kasketis/netfox#142] opened 2018-09-21 18:21 UTC

**Comment by kasketis** [comment] 2018-09-21 20:39
Without a description nobody can help you

**Comment by CavalcanteLeo** [comment] 2018-09-21 21:30
version 1.12.1

My project is in objective-c, and i can't compile it anymore, it says netfox and 3 others need to update to swift 4.2

I will send some screenshot in a bit

**Comment by CavalcanteLeo** [comment] 2018-09-21 21:32
<img width="1279" alt="captura de tela 2018-09-21 as 18 28 00" src="https://user-images.githubusercontent.com/1735944/45906974-8492ee80-bdcc-11e8-8a8e-78d32dd4e5e1.png">


<img width="1278" alt="captura de tela 2018-09-21 as 18 31 49" src="https://user-images.githubusercontent.com/1735944/45907002-a7250780-bdcc-11e8-9be3-27b42e65b5c8.png">

**Comment by Janglinator** [comment] 2018-09-21 21:39
Hmm I'll take a look.  What does your podfile look like?  Do you do any post-install settings?

**Comment by CavalcanteLeo** [comment] 2018-09-24 15:31
Thank u

**Comment by felipeflorencio** [comment] 2018-09-25 10:00
I don't know about the hole project or something like, but one thing, try to use swift 4.0. You will not miss anything for now and will build, as the library still use swift 4, try go to "Build Settings" and look for "Swift Language Version", set for Swift 4, as the error's are not that clear, try to set this to your app target if not set as swift 4.
You can even do better, set this to the specific pod framework if not work, because doing this you will be able to get back working and discover which library is not building anymore on swift 4.

Let me know if help for now at least get back to work

**Comment by hardikdevios** [comment] 2018-10-19 17:46
Any Update Guys ?

**Comment by Janglinator** [comment] 2018-10-23 19:02
Wow, I'm so sorry guys.  I merged in #140 and totally forgot to produce a new release.  Pushing now

**Comment by caipivara** [comment] 2018-11-07 17:38
I tried `1.13.0` with swift 4 and Im getting:

```
/.../Pods/netfox/netfox/iOS/NFXDetailsController_iOS.swift:322:50: 'ActivityType' is not a member type of 'UIActivity'
```

![screen shot 2018-11-07 at 12 38 11 pm](https://user-images.githubusercontent.com/76348/48149424-04482000-e28a-11e8-983b-1469a8af8e13.jpg)

**Comment by vGubriienko** [comment] 2021-12-22 08:43
Thanks for your report! Currently we can't reproduce the issue and close it. You could reopen it anytime if you still can reproduce it.

**Closed by vGubriienko** 2021-12-22 08:43 UTC
