### ISSUE TITLE
Request timeout when uploading file using Multi-part Post request

### ISSUE THREAD

**Issue by rajanbalana1mg** [kasketis/netfox#116] opened 2018-03-12 10:56 UTC

**Comment by kasketis** [comment] 2018-03-12 11:02
Hi, 
Please provide more details about the issue (what version do you use, request executed natively or via 3rd party library, steps to reproduce, etc)

**Comment by rajanbalana1mg** [comment] 2018-03-12 11:12
Environment:

OS: iOS 11
Networking Library: AFNetworking (2.6.3)

Steps to reproduce: 

Step 1: Make a request to the HTTPS Server, request type should be Multi-part POST

Step 2: Observe till the request timeout. You will see the following error:

Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x600000c43e40 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=URL_HERE, NSErrorFailingURLKey=URL_HERE, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

Let me know, if you need any more details

**Comment by kasketis** [comment] 2018-03-12 11:23
Thanks for the info. Are you sure the timeout is related with the netfox e.g if you disable netfox the request is executed successfully?

**Comment by rajanbalana1mg** [comment] 2018-03-12 11:47
Absolutely. I tried the same, as soon as I disable the library. Request goes through.

**Comment by kasketis** [comment] 2018-03-12 11:56
Is it easy to execute the same request using Apple's standard API + netfox?

**Comment by rajanbalana1mg** [comment] 2018-03-12 12:03
Yes. It must be very straight-forward. However, I haven't tried the same.

**Comment by kasketis** [comment] 2018-03-12 12:07
I meant if it is easy you to try it :)

**Comment by Janglinator** [comment] 2018-03-15 05:08
[TEST.zip](https://github.com/kasketis/netfox/files/1814023/TEST.zip)
@kasketis I uploaded a quick test application above.  I'm not quite sure what's going wrong, would you be able to check it out?

P.S. no, there's no viruses in the link.  [Here's](https://www.virustotal.com/#/url/25f7ed6405e22c2bc4e288aa0c242b9b7d9e3e39b5c3b024b0c06db99ddf96c3/detection) proof

**Comment by Janglinator** [comment] 2018-03-15 05:20
Also,  I noticed when we do a regular post, the "Request" column doesn't show my `[foo:bar]` dictionary.

**Comment by kasketis** [comment] 2018-03-15 07:46
Thanks @Janglinator! I reproduced the timeout issue but I want to dive into it more.
Regarding the body issue you mentioned above, I think it is related with [this](https://github.com/kasketis/netfox/blob/master/Workarounds.md#no-http-body-for-requests) (check the radar)
You can view it on multipart possibly because it sent as httpBodyStream and not as httpBody

**Comment by jjjjjeffrey** [comment] 2018-03-20 06:43
I have same issue when using Alamofire to upload file with a steam, 1.10.5 does not have this issue.

**Comment by Janglinator** [comment] 2018-03-20 11:30
Netfox 1.10.5 doesn’t have this issue?  Interesting!

**Comment by jjjjjeffrey** [comment] 2018-03-21 02:17
@Janglinator file uploading can success when I use 1.10.5, but it will be timeout with last version.

**Comment by rajanbalana** [comment] 2018-03-26 17:27
Hey, Did you get the time to look into the issue? I tried to look into the code but was unable to understand the underlying issue.

**Comment by alextud** [comment] 2018-03-28 07:53
I think that issue is related to this pull. https://github.com/kasketis/netfox/pull/102. There is an inputstream that is open / read simultaneous by 2 actors. And this may cause some callbacks/delegates to not be triggered.

**Comment by rajanbalana** [comment] 2018-04-25 07:26
Any update?

**Comment by alextud** [comment] 2018-04-25 08:33
hey we've made a pull request for this issue see https://github.com/kasketis/netfox/pull/120

**Comment by rajanbalana** [comment] 2018-04-25 09:45
@alextud That works! I have integrated your fork into my project. Thanks a ton!

**Comment by felipeflorencio** [comment] 2018-09-21 12:44
As far I see was fixed by @alextud , and his update already was merged 👍 , so, if anyone still get any issue regarding this let us know

**Closed by felipeflorencio** 2018-09-21 12:44 UTC
Labels: bug, help wanted

**Comment by RolandasRazma** [comment] 2019-06-27 10:26
not sure how is this fixed. We see same behaviour in v1.15.0 (any above 1.10.5) when posting multipart forms. Adding `NFXProtocol.self` to URLSessionConfiguration doesn't help either

**Comment by LittleYuz** [comment] 2019-07-18 11:40
same with @RolandasRazma

**Comment by LittleYuz** [comment] 2019-07-18 11:40
same as @RolandasRazma

**Comment by ankitgarg1mg** [comment] 2020-07-24 08:07
Still getting same issue in 1.9.0. @felipeflorencio can you please look into this

**Comment by ismailkilic** [comment] 2020-07-27 11:54
> Still getting same issue in 1.9.0. @felipeflorencio can you please look into this

I agree with you, we still have this issue.
