### ISSUE TITLE
Xcode 10.2 carthage update, no Build

### ISSUE THREAD

**Issue by 1055843615** [kasketis/netfox#155] opened 2019-03-26 12:24 UTC

**Comment by donpironet** [comment] 2019-04-05 08:53
+1

**Comment by silnose** [comment] 2019-06-28 18:11
same with cocoapod

**Comment by vGubriienko** [comment] 2021-12-22 08:43
Thanks for your report! Currently we can't reproduce the issue and close it. You could reopen it anytime if you still can reproduce it.

**Comment by 1055843615** [comment] 2021-12-22 08:44
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed by vGubriienko** 2021-12-22 08:43 UTC
