### ISSUE TITLE
Close button doesn't work after navigating to settings view

### ISSUE THREAD

**Issue by olcayertas** [kasketis/netfox#182] opened 2019-12-12 10:33 UTC
I ahve just installed lates `Debug` config with `CocoaPods`:

`pod 'netfox', :configurations => ['Debug']`

After navigating to settings screen close button doesn't work.

**Comment by vGubriienko** [comment] 2021-12-20 19:01
Thanks for your report! Currently we can't reproduce the issue and close it. You could reopen it anytime if you still can reproduce it.

**Closed by vGubriienko** 2021-12-20 19:01 UTC
