### ISSUE TITLE
Xcode10.2 compile error

### ISSUE THREAD

**Issue by CodeEagle** [kasketis/netfox#150] opened 2019-01-28 01:36 UTC
![image](https://user-images.githubusercontent.com/2311352/51810013-1dd49300-22e0-11e9-886e-6f39afd40e02.png)

**Comment by felipeflorencio** [comment] 2019-02-10 14:41
Make sense, but let's wait until Xcode 10.2 get released to the public, as for now it's still in beta, please let me if still persist when Xcode come out of beta

**Comment by aksvenk** [comment] 2019-04-03 01:19
Any movement on this? XCode 10.2 is now released to the public.

**Comment by felipeflorencio** [comment] 2019-04-08 13:47
Guys really sorry the delay had being crazy. Will be updated until the end of this week for sure getting back from holiday.

**Comment by vGubriienko** [comment] 2021-12-22 08:41
Thanks for your report! Currently we can't reproduce the issue and close it. You could reopen it anytime if you still can reproduce it.

**Closed by vGubriienko** 2021-12-22 08:41 UTC
